export enum TransportProduct {
  InterCityExpress = 'InterCityExpress',
  InterCity = 'InterCity',
  EuroCity = 'EuroCity',
  EuroCityDirect = 'EuroCityDirect',
  EuroNight = 'EuroNight',
  EuropeanSleeper = 'EuropeanSleeper',
  RailJet = 'RailJet',
  RailJetExpress = 'RailJetExpress',
  NightJet = 'NightJet',
  TrainAGrandeVitesse = 'TrainAGrandeVitesse',
  WestBahn = 'WestBahn',
  Eurostar = 'Eurostar',
  FlixTrain = 'FlixTrain',
  InterRegioExpress = 'InterRegioExpress',
  MetropolExpress = 'MetropolExpress',
  FlughafenExpress = 'FlughafenExpress',
  RegionalExpress = 'RegionalExpress',
  Regional  = 'Regional Express',
  Suburban  = 'Suburban ',
  Ferry  = 'Ferry ',
  Underground  = 'Underground ',
  Tram = 'Tram ',
  Bus  = 'Bus ',
  Taxi = 'Taxi',
  Unknown  = 'Unknown ',
}
